### PR TITLE
pull request for gnome-shell-extension-duolingo-status

### PR DESCRIPTION
**Pull request by adaschma**
Hi bo32,

I really like your duolingo gnome-shell extension. In this pull-request are 3 changes that I hope you like:
- Support gnome-shell 3.18 (which is now in Debian Sid; only needed changes in the metadata)
- use of https instead of http
- have the day change of the extension match the one on the duolingo website

If you have any questions or have comments on the patches, I would be glad to hear them. Anyhow, thanks for your nice work.

--Adam Schmalhofer

### CODE REVIEW

**Comment by bo32** [comment]
Hi Adam,
Sorry for the late reply. And thanks for your interest and the improvements :)
Yes definitely, the **version 3.18**, i was going to do it very soon.
However, the **https** seems a bit useless since all the transferred information is public.
Furthermore, I don't really understand the use of TimeZone. **new Date()** is well according to your time zone, and so are the raw timestamps returned by Duolingo (in the **get_improvement** function). On the other hand, I like your idea to compare the timestamps, it avoids several conversions to dates. Can you maybe please explain me why we should use TimeZone? And I see you use the location **America/New_York**. Would it be still accurate for European users, like me for example ;) ? (yes sorry, I'm not a master with the dates, and the GLib documentation is quite light about it) 
Cheers
David

**Comment by adaschma** [comment]
Hi David,

David wrote:

> Sorry for the late reply. And thanks for your interest and the improvements :)
> Yes definitely, the **version 3.18**, i was going to do it very soon.

:-)

> However, the **https** seems a bit useless since all the transferred
> information is public.

I'm not really worried about the transfered data from duolingo. I'm not
happy about the url I am transferring to duolingo. If I'm on a public
WLAN-network and they see http://duolingo.com/users/adamschmalhofer then
it will be easy to guess who it was. And even if my user name would be
a random pseudonym they would know every time I would be there. I don't
feel too good about that.

> Furthermore, I don't really understand the use of
> TimeZone. **new Date()** is well according to your time zone, and so are the
> raw timestamps returned by Duolingo (in the **get_improvement** function). On
> the other hand, I like your idea to compare the timestamps, it avoids several
> conversions to dates. Can you maybe please explain me why we should use
> TimeZone? And I see you use the location **America/New_York**. Would it be
> still accurate for European users, like me for example ;) ?

Well, actually I'm a European user, too (from Germany). If I go to the
duolingo web page at 0:10 (a.m.) or 5:40 (a.m.) MET it still tells me
that I have the XP from the previous day. If I OTOH I push refresh on
the extension without this patch being applied it turns red and shows 0
XP. At 6:02 (a.m.) MET the web page is on the new day and shows 0 XP, too.
That is how I noticed the offset of the time zone duolingo uses. Then I
noticed that duolingo "was started in Pittsburgh" (Wikipedia[1]). Both
of these observations match the time zone America/New_York).

[1] https://en.wikipedia.org/wiki/Duolingo

> (yes sorry, I'm
> not a master with the dates, and the GLib documentation is quite light about
> it) Cheers David

I'm the person who should apologies for not documenting my commits
(enough).

--Adam

**Comment by bo32** [comment]
This is strange... For me, when I refresh at 00:01, my duolingo icon becomes red, so my system recognizes well my location (i'm on fedora).
What's the result of the command **date** in the terminal?
Maybe check also the time zone settings of your linux.
For example, I set it on Brazil, and displayed the date returned in the function **get_improvement()** with a global.log. It returns me the date time according to the time zone of Brazil. I set it back to Copenhagen, where I live, refreshed gnome-shell (alt + f2 then r), and the displayed date time is according to the time zone in Copenhagen. Maybe it's a problem of configuration of your system.

**Comment by adaschma** [comment]
David wrote:

> This is strange... For me, when I refresh at 00:01, my duolingo icon becomes
> red, so my system recognizes well my location (i'm on fedora).

That's no different for me (without the patch). And that is the problem.
This is different from duolingo.com (the web page). The web page doesn't
follow my time zone. As they are different the extension might "give me
a streak" and the web page won't.

> What's the result of the command **date** in the terminal?

$ date
Do 22. Okt 23:20:19 CEST 2015

The time zone matches my local zone, but not the zone used at
duolingo.com.

--Adam

**Comment by bo32** [comment]
This is strange again ;)
I just check my account on duolingo webpage now, so a couple of minutes past midnight, and my score is set bak to 0. So the webpage follows my time zone, and so does my android app.
I hope I will be able to slightly change your pull request and commit it all on saturday.
And thanks for the contribution :)

**Comment by adaschma** [comment]
At one point my account has switched to use my local time. No idea why. Strange indeed. Just happy that it works now (without any additional patches :-).

**Pull request merged**
